- name: demo on functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"

- name: convert to uppercase
  hosts: local
  connection: local
  vars:
    greeting: "Hello Harika"
  ansible.builtin.debug:
    msg: "{{ greeting | upper }}"
    

- name: convert to 
  hosts: local
  connection: local
  vars:
    greeting: "Hello Harika"
  ansible.builtin.debug:
    msg: "{{ greeting | lower }}"            

    