- name: demo on functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"

  - name: convert to uppercase
    vars:
      greeting: "Hello Harika"
    ansible.builtin.debug:
      msg: " {{ greeting | upper }}"

  - name: convert to lowercase
    vars:
      greeting: "Hello Harika"
    ansible.builtin.debug:
      msg: " {{ greeting | lower }}"          

  - name: unique numbers
    vars:
      numbers: [1,2,3,2,4,5,2]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

  - name: minimum and maximum numbers
    vars:
      numbers: [1,2,3,2,4,5,2]
    ansible.builtin.debug:
      msg: "Min: {{ numbers | min }}, Max: {{ numbers | max }}"

  - name: convert map to list
    vars:
      course: Devops
      duration: 102
    ansible.builtin.debug:
      msg: "{{ vars | dict2items }}"